"""create v1 schema

Revision ID: 3017e5ac5b2e
Revises: 0001_skeleton
Create Date: 2026-08-26 11:17:48.281617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3017e5ac5b2e'
down_revision: Union[str, None] = '0001_skeleton'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awaited_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_participant_id', sa.Integer(), nullable=False),
    sa.Column('expected_response_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SATISFIED', 'EXPIRED', 'CANCELLED', 'AMBIGUOUS', name='awaited_response_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_participant_id'], ['task_participant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('awaited_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awaited_response_task_participant_id'), ['task_participant_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=500), nullable=False),
    sa.Column('sender_identity_id', sa.Integer(), nullable=False),
    sa.Column('provider_reply_to_message_id', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id', 'sender_identity_id'], ['conversation_participant.conversation_id', 'conversation_participant.identity_id'], name='fk_message_sender_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id', 'current_revision_id'], ['message_revision.message_id', 'message_revision.id'], name='fk_message_current_revision_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_identity_id'], ['identity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'provider_message_id', name='uq_message_provider_identity'),
    sa.UniqueConstraint('id', 'current_revision_id', name='uq_message_current_parent')
    )
    op.create_table('message_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('provider_revision_key', sa.String(length=500), nullable=False),
    sa.Column('provider_sequence', sa.Integer(), nullable=True),
    sa.Column('provider_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_support', sa.Enum('SUPPORTED', 'UNSUPPORTED', name='content_support', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awaited_response_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(processing_status = 'PROCESSING' AND lease_expires_at IS NOT NULL) OR (processing_status <> 'PROCESSING' AND lease_expires_at IS NULL)", name='ck_revision_processing_lease'),
    sa.CheckConstraint('is_deleted = 0 OR text IS NULL', name='ck_revision_deleted_text'),
    sa.ForeignKeyConstraint(['awaited_response_id'], ['awaited_response.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'id', name='uq_revision_parent_id'),
    sa.UniqueConstraint('message_id', 'provider_revision_key', name='uq_revision_provider_key')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=False),
    sa.Column('default_time', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_location', sa.String(length=500), nullable=True),
    sa.Column('default_topic_key', sa.String(length=300), nullable=False),
    sa.Column('next_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('default_duration_minutes > 0', name='ck_definition_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_definition_next_occurrence_at'), ['next_occurrence_at'], unique=False)

    op.create_table('task_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.Enum('UNKNOWN', 'AVAILABLE', 'UNAVAILABLE', 'UNCERTAIN', name='availability_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('availability_evidence', sa.Enum('FIRST_PARTY', 'THIRD_PARTY', name='availability_evidence', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('availability_source_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(availability_status = 'UNKNOWN' AND availability_evidence IS NULL AND availability_source_revision_id IS NULL) OR (availability_status <> 'UNKNOWN' AND availability_evidence IS NOT NULL AND availability_source_revision_id IS NOT NULL)", name='ck_participant_availability_evidence'),
    sa.ForeignKeyConstraint(['availability_source_revision_id'], ['message_revision.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_instance_id', 'id', name='uq_task_participant_parent_id'),
    sa.UniqueConstraint('task_instance_id', 'person_id', name='uq_task_participant_person')
    )
    op.create_table('telegram_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_update_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='telegram_update_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_update_id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beeper_conversation_id', sa.String(length=400), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('DIRECT', 'GROUP', name='conversation_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('counterparty_person_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind = 'DIRECT' OR counterparty_person_id IS NULL", name='ck_conversation_counterparty_direct'),
    sa.ForeignKeyConstraint(['counterparty_person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beeper_conversation_id')
    )
    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('beeper_user_id', sa.String(length=300), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beeper_user_id')
    )
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_person_id'), ['person_id'], unique=False)

    op.create_table('message_processing_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_revision_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILED', 'ABANDONED', name='processing_attempt_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('failure_type', sa.Enum('TIMEOUT', 'MODEL_ERROR', 'CORRELATION_ERROR', 'INVALID_DATA', 'INTERNAL_ERROR', name='processing_failure_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.CheckConstraint('(finished_at IS NULL AND result IS NULL) OR (finished_at IS NOT NULL AND result IS NOT NULL)', name='ck_processing_attempt_finished_result'),
    sa.ForeignKeyConstraint(['message_revision_id'], ['message_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_definition_participant',
    sa.Column('task_definition_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definition.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('task_definition_id', 'person_id')
    )
    op.create_table('task_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_key', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('topic_key', sa.String(length=300), nullable=False),
    sa.Column('coordination_close_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'LAPSED', name='task_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(task_definition_id IS NULL AND occurrence_key IS NULL) OR (task_definition_id IS NOT NULL AND occurrence_key IS NOT NULL)', name='ck_instance_definition_occurrence_pair'),
    sa.CheckConstraint('coordination_close_offset_minutes >= 0', name='ck_instance_close_offset_nonnegative'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_instance_duration_positive'),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definition.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_definition_id', 'occurrence_key', name='uq_instance_occurrence')
    )
    with op.batch_alter_table('task_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_instance_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('contact_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'TOPIC', 'TASK_DEFINITION', 'TASK_INSTANCE', name='contact_rule_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('USER_CONFIGURED', 'PARTICIPANT_REQUESTED', 'SYSTEM_INFERRED', name='contact_rule_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('strength', sa.Enum('WEAK', 'MEDIUM', 'STRONG', name='contact_rule_strength', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('topic_key', sa.String(length=300), nullable=True),
    sa.Column('task_definition_id', sa.Integer(), nullable=True),
    sa.Column('task_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=50), nullable=True),
    sa.Column('overrides_contact_rule_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(revoked_at IS NULL AND revoked_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_reason IN ('REVOKED','SUPERSEDED'))", name='ck_contact_rule_revocation'),
    sa.CheckConstraint("(scope = 'GLOBAL' AND topic_key IS NULL AND task_definition_id IS NULL AND task_instance_id IS NULL) OR (scope = 'TOPIC' AND topic_key IS NOT NULL AND task_definition_id IS NULL AND task_instance_id IS NULL) OR (scope = 'TASK_DEFINITION' AND topic_key IS NULL AND task_definition_id IS NOT NULL AND task_instance_id IS NULL) OR (scope = 'TASK_INSTANCE' AND topic_key IS NULL AND task_definition_id IS NULL AND task_instance_id IS NOT NULL)", name='ck_contact_rule_scope_target'),
    sa.CheckConstraint('overrides_contact_rule_id IS NULL OR overrides_contact_rule_id <> id', name='ck_contact_rule_no_self_override'),
    sa.ForeignKeyConstraint(['overrides_contact_rule_id'], ['contact_rule.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_rule_person_id'), ['person_id'], unique=False)

    op.create_table('conversation_participant',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('conversation_id', 'identity_id')
    )
    op.create_table('disclosure_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_person_id', sa.Integer(), nullable=False),
    sa.Column('source_conversation_id', sa.Integer(), nullable=False),
    sa.Column('destination_conversation_id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='disclosure_grant_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('inactive_reason', sa.Enum('EXPIRED', 'REVOKED', 'TASK_TERMINAL', name='disclosure_inactive_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND inactive_reason IS NULL) OR (status = 'INACTIVE' AND inactive_reason IS NOT NULL)", name='ck_disclosure_status_reason'),
    sa.CheckConstraint('source_conversation_id <> destination_conversation_id', name='ck_disclosure_cross_conversation'),
    sa.ForeignKeyConstraint(['destination_conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disclosure_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosure_grant_task_instance_id'), ['task_instance_id'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_participant_id', sa.Integer(), nullable=True),
    sa.Column('source_message_revision_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('proposed_value', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'SUPERSEDED', 'PARENT_TERMINAL', name='proposal_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'PENDING' AND resolved_at IS NULL) OR (status <> 'PENDING' AND resolved_at IS NOT NULL)", name='ck_proposal_resolution'),
    sa.ForeignKeyConstraint(['source_message_revision_id'], ['message_revision.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id', 'proposed_by_participant_id'], ['task_participant.task_instance_id', 'task_participant.id'], name='fk_proposal_participant_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('task_participant_id', sa.Integer(), nullable=True),
    sa.Column('source_message_revision_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_message_revision_id'], ['message_revision.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_participant_id'], ['task_participant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_event_task_instance_id'), ['task_instance_id'], unique=False)

    op.create_table('task_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('stop_condition_json', sa.JSON(), nullable=True),
    sa.Column('target_selector', sa.Enum('ALL_PARTICIPANTS', 'NO_RESPONSE', 'AVAILABLE', 'UNAVAILABLE', 'UNCERTAIN', 'SPECIFIC_PARTICIPANT', name='target_selector', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_task_participant_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('SEND_MESSAGE', name='trigger_action_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('action_payload_json', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='trigger_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('inactive_reason', sa.Enum('FIRED', 'STOP_CONDITION_MET', 'DISABLED', 'TASK_TERMINAL', name='trigger_inactive_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND inactive_reason IS NULL) OR (status = 'INACTIVE' AND inactive_reason IS NOT NULL)", name='ck_trigger_status_reason'),
    sa.CheckConstraint("(target_selector = 'SPECIFIC_PARTICIPANT' AND target_task_participant_id IS NOT NULL) OR (target_selector <> 'SPECIFIC_PARTICIPANT' AND target_task_participant_id IS NULL)", name='ck_trigger_specific_target'),
    sa.ForeignKeyConstraint(['task_instance_id', 'target_task_participant_id'], ['task_participant.task_instance_id', 'task_participant.id'], name='fk_trigger_participant_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_trigger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_trigger_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('disclosure_grant_scope',
    sa.Column('disclosure_grant_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('AVAILABILITY', 'SCHEDULING', 'LOCATION', name='disclosure_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_grant_id'], ['disclosure_grant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('disclosure_grant_id', 'scope')
    )
    op.create_table('trigger_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_trigger_id', sa.Integer(), nullable=False),
    sa.Column('fire_key', sa.String(length=300), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='trigger_execution_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'PROCESSING' AND lease_expires_at IS NOT NULL) OR (status <> 'PROCESSING' AND lease_expires_at IS NULL)", name='ck_trigger_execution_lease'),
    sa.ForeignKeyConstraint(['task_trigger_id'], ['task_trigger.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_trigger_id', 'fire_key', name='uq_trigger_execution_fire')
    )
    op.create_table('outbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=True),
    sa.Column('transport', sa.Enum('BEEPER', 'TELEGRAM', name='transport', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('destination_kind', sa.Enum('PARTICIPANT', 'OWNER', name='destination_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('message_kind', sa.Enum('INITIAL', 'REMINDER', 'CLARIFICATION', 'UPDATE', 'NOTIFICATION', 'CORRECTION', name='message_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', 'RECONCILING', 'CANCELLED', name='outbox_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_terminal_policy', sa.Enum('TERMINATE', 'SURVIVE', name='outbox_parent_terminal_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cancel_reason', sa.Enum('PARENT_TERMINAL', 'STALE', 'POLICY_BLOCKED', name='outbox_cancel_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('trigger_execution_id', sa.Integer(), nullable=True),
    sa.Column('corrects_outbox_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(message_kind = 'CORRECTION' AND corrects_outbox_message_id IS NOT NULL) OR (message_kind <> 'CORRECTION' AND corrects_outbox_message_id IS NULL)", name='ck_outbox_correction_link'),
    sa.CheckConstraint("(status = 'CANCELLED' AND cancel_reason IS NOT NULL) OR (status <> 'CANCELLED' AND cancel_reason IS NULL)", name='ck_outbox_cancel_reason'),
    sa.CheckConstraint("(status = 'SENDING' AND lease_expires_at IS NOT NULL) OR (status <> 'SENDING' AND lease_expires_at IS NULL)", name='ck_outbox_sending_lease'),
    sa.CheckConstraint("(transport = 'BEEPER' AND destination_kind = 'PARTICIPANT') OR (transport = 'TELEGRAM' AND destination_kind = 'OWNER')", name='ck_outbox_transport_destination'),
    sa.CheckConstraint('corrects_outbox_message_id IS NULL OR corrects_outbox_message_id <> id', name='ck_outbox_no_self_correction'),
    sa.ForeignKeyConstraint(['corrects_outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trigger_execution_id'], ['trigger_execution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corrects_outbox_message_id'),
    sa.UniqueConstraint('transport', 'idempotency_key', name='uq_outbox_transport_idempotency')
    )
    op.create_table('awaited_response_prompt',
    sa.Column('awaited_response_id', sa.Integer(), nullable=False),
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['awaited_response_id'], ['awaited_response.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('awaited_response_id', 'outbox_message_id')
    )
    op.create_table('beeper_outbox_destination',
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outbox_message_id')
    )
    op.create_table('decision_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLOSED', name='decision_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('close_reason', sa.Enum('ANSWERED', 'DISMISSED', 'EXPIRED', 'PARENT_TERMINAL', 'SUBJECT_RESOLVED', name='decision_close_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_json', sa.JSON(), nullable=True),
    sa.Column('parent_terminal_policy', sa.Enum('TERMINATE', 'SURVIVE', name='decision_parent_terminal_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('contact_rule_id', sa.Integer(), nullable=True),
    sa.Column('outbox_message_id', sa.Integer(), nullable=True),
    sa.Column('message_revision_id', sa.Integer(), nullable=True),
    sa.Column('telegram_update_id', sa.Integer(), nullable=True),
    sa.Column('trigger_execution_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(status = 'PENDING' AND close_reason IS NULL AND resolved_at IS NULL AND resolution_json IS NULL) OR (status = 'CLOSED' AND close_reason IS NOT NULL AND resolved_at IS NOT NULL AND ((close_reason = 'ANSWERED' AND resolution_json IS NOT NULL) OR (close_reason <> 'ANSWERED' AND resolution_json IS NULL)))", name='ck_decision_resolution'),
    sa.CheckConstraint('(proposal_id IS NOT NULL) + (contact_rule_id IS NOT NULL) + (outbox_message_id IS NOT NULL) + (message_revision_id IS NOT NULL) + (telegram_update_id IS NOT NULL) + (trigger_execution_id IS NOT NULL) = 1', name='ck_decision_exactly_one_subject'),
    sa.ForeignKeyConstraint(['contact_rule_id'], ['contact_rule.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_revision_id'], ['message_revision.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['telegram_update_id'], ['telegram_update.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trigger_execution_id'], ['trigger_execution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_delivery_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILED', 'ABANDONED', name='delivery_attempt_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('failure_type', sa.String(length=100), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=500), nullable=True),
    sa.CheckConstraint('(finished_at IS NULL AND result IS NULL) OR (finished_at IS NOT NULL AND result IS NOT NULL)', name='ck_delivery_attempt_finished_result'),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_delivery_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_delivery_attempt_outbox_message_id'), ['outbox_message_id'], unique=False)
        batch_op.create_index('uq_delivery_attempt_unfinished', ['outbox_message_id'], unique=True, sqlite_where=sa.text('finished_at IS NULL'))

    op.create_table('outbox_message_participant',
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.Column('task_participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_participant_id'], ['task_participant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outbox_message_id', 'task_participant_id')
    )
    op.create_table('telegram_outbox_destination',
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outbox_message_id')
    )
    op.create_table('beeper_delivery_attempt_detail',
    sa.Column('outbox_delivery_attempt_id', sa.Integer(), nullable=False),
    sa.Column('pending_provider_id', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['outbox_delivery_attempt_id'], ['outbox_delivery_attempt.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outbox_delivery_attempt_id')
    )
    op.create_table('decision_request_awaited_response_candidate',
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('awaited_response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['awaited_response_id'], ['awaited_response.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_request.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_request_id', 'awaited_response_id')
    )
    op.create_table('decision_request_prompt',
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('outbox_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_request.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outbox_message_id'], ['outbox_message.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_request_id'),
    sa.UniqueConstraint('outbox_message_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_request_prompt')
    op.drop_table('decision_request_awaited_response_candidate')
    op.drop_table('beeper_delivery_attempt_detail')
    op.drop_table('telegram_outbox_destination')
    op.drop_table('outbox_message_participant')
    with op.batch_alter_table('outbox_delivery_attempt', schema=None) as batch_op:
        batch_op.drop_index('uq_delivery_attempt_unfinished', sqlite_where=sa.text('finished_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_outbox_delivery_attempt_outbox_message_id'))

    op.drop_table('outbox_delivery_attempt')
    op.drop_table('decision_request')
    op.drop_table('beeper_outbox_destination')
    op.drop_table('awaited_response_prompt')
    op.drop_table('outbox_message')
    op.drop_table('trigger_execution')
    op.drop_table('disclosure_grant_scope')
    with op.batch_alter_table('task_trigger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_trigger_next_run_at'))

    op.drop_table('task_trigger')
    with op.batch_alter_table('task_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_event_task_instance_id'))

    op.drop_table('task_event')
    op.drop_table('proposal')
    with op.batch_alter_table('disclosure_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosure_grant_task_instance_id'))

    op.drop_table('disclosure_grant')
    op.drop_table('conversation_participant')
    with op.batch_alter_table('contact_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_rule_person_id'))

    op.drop_table('contact_rule')
    with op.batch_alter_table('task_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_instance_scheduled_at'))

    op.drop_table('task_instance')
    op.drop_table('task_definition_participant')
    op.drop_table('message_processing_attempt')
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_person_id'))

    op.drop_table('identity')
    op.drop_table('conversation')
    op.drop_table('telegram_update')
    op.drop_table('task_participant')
    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_definition_next_occurrence_at'))

    op.drop_table('task_definition')
    op.drop_table('person')
    op.drop_table('message_revision')
    op.drop_table('message')
    with op.batch_alter_table('awaited_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awaited_response_task_participant_id'))

    op.drop_table('awaited_response')
    # ### end Alembic commands ###
