"""Pure deterministic rendering for typed owner-decision prompts; owns no state."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Protocol
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


class BoundaryPromptCandidate(Protocol):
    task_instance_id: int
    topic_key: str


@dataclass(frozen=True, slots=True)
class CounterproposalPromptContext:
    participant_name: str
    topic_key: str
    scheduled_at: datetime
    duration_minutes: int
    location: str | None
    owner_timezone: str


OrderingPromptCandidate = tuple[
    int,
    str | None,
    int | None,
    str | None,
    str,
]
ORDERING_TEXT_PREVIEW_MAX_LENGTH = 240


def uncertain_delivery_prompt(outbox_id: int) -> str:
    return (
        f"Delivery for outbox {outbox_id} is uncertain. It must not be retried. "
        "Reply to this Telegram message with `keep reconciling` to acknowledge while "
        "leaving it blocked."
    )


def validator_block_prompt(outbox_id: int) -> str:
    return (
        f"Outbox {outbox_id} was blocked by independent validation. Its immutable text "
        "will not be sent or regenerated by the worker. Reply to this Telegram message "
        "with `keep blocked` to acknowledge."
    )


def owner_command_review_prompt(telegram_update_id: int) -> str:
    return (
        f"Telegram command {telegram_update_id} requires owner review and was not applied. "
        "Reply to this Telegram message with `dismiss`, then submit a corrected command "
        "separately."
    )


def mass_contact_confirmation_prompt(
    *, task_id: int, participant_count: int, threshold: int
) -> str:
    return (
        f"Task {task_id} would contact {participant_count} distinct participants, "
        f"which exceeds the mass-contact threshold of {threshold}. "
        "No participant messages will be sent until you decide. Reply to this "
        "Telegram message with `approve mass contact` or `cancel task`."
    )


def legacy_counterproposal_prompt(
    field: str, operation: str, proposed_value: object
) -> str:
    return (
        f"Participant proposed {field} {operation}: {proposed_value}. "
        "Reply to this Telegram message with `approve` or `reject`."
    )


def counterproposal_prompt(
    *,
    context: CounterproposalPromptContext,
    field: str,
    operation: str,
    proposed_value: object,
) -> str:
    if operation != "SET":
        raise ValueError("counterproposal prompt requires the canonical SET operation")

    if field == "scheduled_at":
        current = _as_utc(context.scheduled_at)
        proposed = _parse_scheduled_value(proposed_value)
        zone = _owner_zone(context.owner_timezone)
        current_local = current.astimezone(zone)
        proposed_local = proposed.astimezone(zone)
        current_date = _format_date(current_local)
        if current_local.date() == proposed_local.date():
            change = f"from {current_date} at {_format_time(current_local)} to {_format_time(proposed_local)}"
        else:
            change = (
                f"from {current_date} at {_format_time(current_local)} to "
                f"{_format_date(proposed_local)} at {_format_time(proposed_local)}"
            )
        detail = (
            f"suggested moving {context.topic_key} {change} "
            f"for {_format_duration(context.duration_minutes)}"
        )
    elif field == "duration_minutes":
        proposed_duration = _parse_duration(proposed_value)
        detail = (
            f"suggested changing the duration for {context.topic_key} from "
            f"{_format_duration(context.duration_minutes)} to "
            f"{_format_duration(proposed_duration)}"
        )
    elif field == "location":
        proposed_location = _parse_location(proposed_value)
        detail = (
            f"suggested changing the location for {context.topic_key} from "
            f"{_format_location(context.location)} to {_format_location(proposed_location)}"
        )
    else:
        raise ValueError(f"unsupported counterproposal field: {field}")

    return (
        f"{context.participant_name} {detail}. Should I accept this change? "
        "Reply to this Telegram message with `approve` or `reject`."
    )


def _as_utc(value: datetime) -> datetime:
    if value.tzinfo is None or value.utcoffset() is None:
        # SQLite does not preserve timezone metadata for the normalized UTC task value.
        value = value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _owner_zone(name: str) -> ZoneInfo:
    try:
        return ZoneInfo(name)
    except ZoneInfoNotFoundError as exc:
        raise ValueError(f"owner timezone is invalid: {name}") from exc


def _parse_scheduled_value(value: object) -> datetime:
    if not isinstance(value, str):
        raise ValueError("scheduled_at proposal must be an ISO timestamp")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError("scheduled_at proposal must be an ISO timestamp") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError("scheduled_at proposal must be timezone-aware")
    return parsed.astimezone(UTC)


def _parse_duration(value: object) -> int:
    if type(value) is not int or value <= 0:
        raise ValueError("duration proposal must be a positive integer")
    return value


def _parse_location(value: object) -> str | None:
    if value is not None and not isinstance(value, str):
        raise ValueError("location proposal must be a string or null")
    return value


def _format_date(value: datetime) -> str:
    return f"{value.strftime('%A, %B')} {value.day}"


def _format_time(value: datetime) -> str:
    return value.strftime("%I:%M %p").lstrip("0")


def _format_duration(value: int) -> str:
    return f"{value} minute" if value == 1 else f"{value} minutes"


def _format_location(value: str | None) -> str:
    return "no location" if value is None else f"“{value}”"


def late_terminal_message_prompt(
    *,
    task_id: int,
    topic_key: str,
    task_status: str,
    sender_name: str,
    revision_id: int,
    participant_text: str | None,
) -> str:
    text = "<deleted>" if participant_text is None else repr(participant_text)
    return (
        f"Late message from {sender_name} for terminal {topic_key} task {task_id} "
        f"({task_status.lower()}), revision {revision_id}.\n"
        f"Untrusted participant text (quoted exactly): {text}\n"
        "Reply to this Telegram message with `dismiss` to acknowledge it."
    )


def late_terminal_message_trusted_claims(
    *,
    task_id: int,
    topic_key: str,
    task_status: str,
    sender_name: str,
    revision_id: int,
) -> tuple[str, ...]:
    return (
        f"Task {task_id} for {topic_key} is terminal with status {task_status.lower()}.",
        f"Revision {revision_id} is a late message from {sender_name} for task {task_id}.",
        "The owner may acknowledge the late message by replying to this Telegram message with `dismiss`.",
    )


def late_terminal_message_untrusted_data(
    *, revision_id: int, participant_text: str | None
) -> tuple[str, ...]:
    text = "<deleted>" if participant_text is None else participant_text
    return (f"revision {revision_id} participant text={text!r}",)


def correlation_ambiguity_prompt(
    candidates: Iterable[tuple[int, str, str, int, int, str]],
) -> str:
    lines = ["Choose the response this message belongs to:"]
    lines.extend(
        f"- {candidate_id}: {topic_key} at {scheduled_at}, participant {person_id}, "
        f"conversation {conversation_id}, expected {expected_response_type}"
        for (
            candidate_id,
            topic_key,
            scheduled_at,
            person_id,
            conversation_id,
            expected_response_type,
        ) in candidates
    )
    lines.append(
        "Reply to this Telegram message with `select <awaited-response-id>`."
    )
    return "\n".join(lines)


def ordering_conflict_prompt(
    candidates: Iterable[OrderingPromptCandidate],
) -> str:
    values = tuple(candidates)
    lines = [
        "Message revision ordering is ambiguous. Choose the authoritative revision:"
    ]
    for trusted_claim, untrusted_value in zip(
        ordering_conflict_trusted_claims(values)[1:-1],
        ordering_conflict_untrusted_data(values),
        strict=True,
    ):
        lines.append(f"- {trusted_claim}")
        lines.append(f"  {untrusted_value}")
    lines.append(
        "Reply to this Telegram message with `select revision <revision-id>`."
    )
    return "\n".join(lines)


def ordering_conflict_trusted_claims(
    candidates: Iterable[OrderingPromptCandidate],
) -> tuple[str, ...]:
    values = tuple(candidates)
    return (
        "Message revision ordering is ambiguous.",
        *(
            f"revision {revision_id} provider ordering: sort={sort_key!r}, "
            f"sequence={sequence!r}, event_at={event_at!r}"
            for revision_id, sort_key, sequence, event_at, _preview in values
        ),
        "The owner may select one listed revision by replying to this Telegram message.",
    )


def ordering_conflict_untrusted_data(
    candidates: Iterable[OrderingPromptCandidate],
) -> tuple[str, ...]:
    return tuple(
        f"revision {revision_id} participant text preview={preview!r}"
        for revision_id, _sort_key, _sequence, _event_at, preview in candidates
    )


def bounded_revision_preview(text: str | None) -> str:
    value = "<deleted>" if text is None else text
    return value[:ORDERING_TEXT_PREVIEW_MAX_LENGTH]


def contact_boundary_ambiguity_prompt(
    decision_id: int, candidates: Iterable[BoundaryPromptCandidate]
) -> str:
    options = tuple(candidates)
    lines = [f"Participant contact boundary decision {decision_id} has ambiguous scope."]
    lines.extend(f"- task {item.task_instance_id}: topic {item.topic_key}" for item in options)
    lines.append(
        "Reply to this Telegram message with `set global`, `set topic <topic-key>`, "
        "`set task <task-id>`, or `dismiss`."
    )
    return "\n".join(lines)


def contact_rule_exception_prompt(
    rule_id: int,
    task_id: int,
    person_name: str,
    scope_description: str,
    participant_text: str,
) -> str:
    return (
        f"{person_name}'s contact rule {rule_id} ({scope_description}) blocks task {task_id}.\n"
        f"Untrusted participant boundary text (quoted exactly): {participant_text!r}\n"
        "Reply to this Telegram message with `allow this task` for one narrow exception "
        "or `respect boundary`."
    )
