"""Pure deterministic rendering for typed owner-decision prompts; owns no state."""

from __future__ import annotations

from collections.abc import Iterable


OrderingPromptCandidate = tuple[
    int,
    str | None,
    int | None,
    str | None,
    str,
]
ORDERING_TEXT_PREVIEW_MAX_LENGTH = 240


def uncertain_delivery_prompt(outbox_id: int) -> str:
    return (
        f"Delivery for outbox {outbox_id} is uncertain. It must not be retried. "
        "Reply to this Telegram message with `keep reconciling` to acknowledge while "
        "leaving it blocked."
    )


def validator_block_prompt(outbox_id: int) -> str:
    return (
        f"Outbox {outbox_id} was blocked by independent validation. Its immutable text "
        "will not be sent or regenerated by the worker. Reply to this Telegram message "
        "with `keep blocked` to acknowledge."
    )


def owner_command_review_prompt(telegram_update_id: int) -> str:
    return (
        f"Telegram command {telegram_update_id} requires owner review and was not applied. "
        "Reply to this Telegram message with `dismiss`, then submit a corrected command "
        "separately."
    )


def counterproposal_prompt(field: str, operation: str, proposed_value: object) -> str:
    return (
        f"Participant proposed {field} {operation}: {proposed_value}. "
        "Reply to this Telegram message with `approve` or `reject`."
    )


def correlation_ambiguity_prompt(
    candidates: Iterable[tuple[int, str, str, int, int, str]],
) -> str:
    lines = ["Choose the response this message belongs to:"]
    lines.extend(
        f"- {candidate_id}: {topic_key} at {scheduled_at}, participant {person_id}, "
        f"conversation {conversation_id}, expected {expected_response_type}"
        for (
            candidate_id,
            topic_key,
            scheduled_at,
            person_id,
            conversation_id,
            expected_response_type,
        ) in candidates
    )
    lines.append(
        "Reply to this Telegram message with `select <awaited-response-id>`."
    )
    return "\n".join(lines)


def ordering_conflict_prompt(
    candidates: Iterable[OrderingPromptCandidate],
) -> str:
    values = tuple(candidates)
    lines = [
        "Message revision ordering is ambiguous. Choose the authoritative revision:"
    ]
    for trusted_claim, untrusted_value in zip(
        ordering_conflict_trusted_claims(values)[1:-1],
        ordering_conflict_untrusted_data(values),
        strict=True,
    ):
        lines.append(f"- {trusted_claim}")
        lines.append(f"  {untrusted_value}")
    lines.append(
        "Reply to this Telegram message with `select revision <revision-id>`."
    )
    return "\n".join(lines)


def ordering_conflict_trusted_claims(
    candidates: Iterable[OrderingPromptCandidate],
) -> tuple[str, ...]:
    values = tuple(candidates)
    return (
        "Message revision ordering is ambiguous.",
        *(
            f"revision {revision_id} provider ordering: sort={sort_key!r}, "
            f"sequence={sequence!r}, event_at={event_at!r}"
            for revision_id, sort_key, sequence, event_at, _preview in values
        ),
        "The owner may select one listed revision by replying to this Telegram message.",
    )


def ordering_conflict_untrusted_data(
    candidates: Iterable[OrderingPromptCandidate],
) -> tuple[str, ...]:
    return tuple(
        f"revision {revision_id} participant text preview={preview!r}"
        for revision_id, _sort_key, _sequence, _event_at, preview in candidates
    )


def bounded_revision_preview(text: str | None) -> str:
    value = "<deleted>" if text is None else text
    return value[:ORDERING_TEXT_PREVIEW_MAX_LENGTH]
